<?php

namespace AppBundle\Repository;

/**
 * AssocUserChatSessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssocUserChatSessionRepository extends \Doctrine\ORM\EntityRepository
{
}
