<?php

namespace AppBundle\Repository;

/**
 * AssocCopieCorrecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssocCopieCorrecteurRepository extends \Doctrine\ORM\EntityRepository
{
}
