<?php

namespace AppBundle\Repository;

/**
 * AssocDocDiscRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssocDocDiscRepository extends \Doctrine\ORM\EntityRepository
{
}
