<?php

namespace AppBundle\Repository;

/**
 * AssocGroupeLiensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssocGroupeLiensRepository extends \Doctrine\ORM\EntityRepository
{
}
