<?php

namespace AppBundle\Repository;

/**
 * AssocDocInscrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssocDocInscrRepository extends \Doctrine\ORM\EntityRepository
{
}
