<?php

namespace AppBundle\Repository;

/**
 * CategorieLienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieLienRepository extends \Doctrine\ORM\EntityRepository
{
}
