<?php

namespace AppBundle\Repository;

/**
 * ChatPostRepository.php
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ChatPostRepository extends \Doctrine\ORM\EntityRepository
{
}
