<?php

namespace AppBundle\Repository;

/**
 * CohorteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CohorteRepository extends \Doctrine\ORM\EntityRepository
{
}
