<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Cohorte;

/**
 * CohorteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CohorteRepository extends \Doctrine\ORM\EntityRepository
{
    public function findInscrits($id)
    {
        $em = $this->getEntityManager();
        $cohorte = $this->findOneBy(array('id'=> $id));

        $users = array();

        $inscrCohs = $em->getRepository('AppBundle:Inscription_coh')->findBy(array('cohorte' => $cohorte));
        if($inscrCohs){
            foreach($inscrCohs as $inscrCoh){
                if(!in_array($inscrCoh->getUser(), $users) && $inscrCoh->getUser()->isEnabled()){
                    array_push($users, $inscrCoh->getUser());
                }
            }
        }
        return $inscrCohs;
    }

    public function userIsInscrit($userId, $cohId)
    {
        return $this->getUserInscr($userId, $cohId)!=null;
    }

    public function getUserInscr($userId, $cohId){
        $em = $this->getEntityManager();
        $coh = $this->findOneBy(array('id'=> $cohId));
        $user = $em->getRepository('AppBundle:User')->findOneBy(array('id' => $userId));

        $insc = $em->getRepository('AppBundle:Inscription_coh')->findBy(array('cohorte' => $coh, 'user' => $user));
        return $insc;
    }

    public function userHasAccessOrIsInscrit($userId, $cohId)
    {
        return $this->userIsInscrit($userId, $cohId);
    }

    public function allForUser($userId)
    {
        $em = $this->getEntityManager();
        $user = $em->getRepository('AppBundle:User')->findOneBy(array('id' => $userId));

        $inscs = $em->getRepository('AppBundle:Inscription_coh')->findBy(array('user' => $user));

        $cohs = array();
        if($inscs){
            foreach($inscs as $insc){
                if(!in_array($insc->getCohorte(), $cohs)){
                    array_push($cohs, $insc->getCohorte());
                }
            }
        }

        return $cohs;
    }

    public function getRole($userId, $id)
    {
        $em = $this->getEntityManager();
        $item = $this->findOneBy(array('id'=> $id));
        $user = $em->getRepository('AppBundle:User')->findOneBy(array('id' => $userId));

        $inscr = $em->getRepository('AppBundle:Inscription_coh')->findOneBy(array('cohorte' => $item, 'user' => $user));
        if($inscr){
            return $inscr->getRole();
        }
        return null;
    }

    public function getLinkedCourses(Cohorte $cohorte)
    {
        $em = $this->getEntityManager();

        $courses = $cohorte->getCours();
        $discs = $cohorte->getDisciplines();
        if($discs){
            $repositoryCours = $em->getRepository('AppBundle:Cours');
            foreach ($discs as $disc){
                $cours_arr = $repositoryCours->findBy(array('discipline' => $disc));
                if($cours_arr) {
                    foreach ($cours_arr as $cours) {
                        if(!$courses->contains($cours)){
                            $courses->add($cours);
                        }
                    }
                }
            }
        }
        return $courses;
    }
}
