<?php

namespace AppBundle\Repository;

/**
 * CopieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CopieRepository extends \Doctrine\ORM\EntityRepository
{
}
