<?php

namespace AppBundle\Repository;

/**
 * CopieFichierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CopieFichierRepository extends \Doctrine\ORM\EntityRepository
{

}
