<?php

namespace AppBundle\Repository;

/**
 * CorrigeFichierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrigeFichierRepository extends \Doctrine\ORM\EntityRepository
{

}
