<?php

namespace AppBundle\Repository;

/**
 * CorrigeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CorrigeRepository extends \Doctrine\ORM\EntityRepository
{
}
