<?php

namespace AppBundle\Repository;

/**
 * DevoirSujetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevoirSujetRepository extends \Doctrine\ORM\EntityRepository
{
}
