<?php

namespace AppBundle\Repository;

/**
 * DevoirCorrigeTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevoirCorrigeTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
