<?php

namespace AppBundle\Repository;

/**
 * DevoirRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevoirRepository extends \Doctrine\ORM\EntityRepository
{
}
