<?php

namespace AppBundle\Repository;

/**
 * DisciplineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DisciplineRepository extends \Doctrine\ORM\EntityRepository
{

    public function findInscrits($id)
    {
        $em = $this->getEntityManager();
        $discipline = $this->findOneBy(array('id'=> $id));

        $users = array();

        $inscrDs = $em->getRepository('AppBundle:Inscription_d')->findBy(array('discipline' => $discipline));
        if($inscrDs){
            foreach($inscrDs as $inscrD){
                if(!in_array($inscrD->getUser(), $users)){
                    array_push($users, $inscrD->getUser());
                }
            }
        }

        $inscrCohs = $em->getRepository('AppBundle:Inscription_coh')->findAll();
        if($inscrCohs){
            foreach($inscrCohs as $inscrCoh){
                $coh = $inscrCoh->getCohorte();

                if($coh->getDisciplines()->contains($discipline)){
                    if(!in_array($inscrCoh->getUser(), $users)){
                        array_push($users, $inscrCoh->getUser());
                    }
                }

            }
        }

        return $users;
    }

    public function userIsInscrit($userId, $disId)
    {
        $em = $this->getEntityManager();
        $dis = $this->findOneBy(array('id'=> $disId));
        $user = $em->getRepository('AppBundle:User')->findOneBy(array('id' => $userId));

        $insc = $em->getRepository('AppBundle:Inscription_d')->findBy(array('discipline' => $dis, 'user' => $user));

        return $insc!=null;
    }

    public function userHasAccess($userId, $coursId)
    {
        $em = $this->getEntityManager();
        $inscrits = $this->findInscrits($coursId);
        $user = $em->getRepository('AppBundle:User')->findOneBy(array('id' => $userId));

        if(in_array($user, $inscrits)){
            return true;
        }else{
            return false;
        }
    }

}
