<?php

namespace AppBundle\Repository;

/**
 * EvtCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvtCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
