<?php

namespace AppBundle\Repository;

/**
 * EvtDisciplineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvtDisciplineRepository extends \Doctrine\ORM\EntityRepository
{
}
