<?php

namespace AppBundle\Repository;

/**
 * EvtUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvtUserRepository extends \Doctrine\ORM\EntityRepository
{
}
