<?php

namespace AppBundle\Repository;

/**
 * GroupeLiensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupeLiensRepository extends \Doctrine\ORM\EntityRepository
{
}
