<?php

namespace AppBundle\Repository;

/**
 * Inscription_dRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Inscription_dRepository extends \Doctrine\ORM\EntityRepository
{
}
