<?php

namespace AppBundle\Repository;

/**
 * Inscription_cohRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Inscription_cohRepository extends \Doctrine\ORM\EntityRepository
{
    public function allForUser($userId)
    {
        $em = $this->getEntityManager();
        $user = $em->getRepository('AppBundle:User')->findOneBy(array('id' => $userId));

        $inscs = $em->getRepository('AppBundle:Inscription_coh')->findBy(array('user' => $user));

        return $inscs;
    }
}