<?php

namespace AppBundle\Repository;

/**
 * Inscription_coh_cRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Inscription_coh_cRepository extends \Doctrine\ORM\EntityRepository
{
}
