<?php

namespace AppBundle\Repository;

/**
 * Mp3PodcastRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Mp3PodcastRepository extends \Doctrine\ORM\EntityRepository
{
}
