<?php

namespace AppBundle\Repository;

/**
 * RessourceLibreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RessourceLibreRepository extends \Doctrine\ORM\EntityRepository
{

}
