<?php

namespace AppBundle\Repository;

/**
 * Role_cohRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Role_cohRepository extends \Doctrine\ORM\EntityRepository
{
}
