<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Inscription_sess;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function userIsInscrit($user, $session)
    {
        $em = $this->getEntityManager();

        $inscSess = $em->getRepository('AppBundle:Inscription_sess')->findBy(array('session' => $session, 'user' => $user));

        return $inscSess;
    }

    public function userHasAccess($user, $sess)
    {
        return $this->userIsInscrit($user, $sess);
    }

    public function userHasAccessOrIsInscrit($user, $sess)
    {
        return $this->userHasAccess($user, $sess) || $this->userIsInscrit($user, $sess);
    }
    public function getRole($user, $item)
    {
        $em = $this->getEntityManager();

        $inscr = $em->getRepository('AppBundle:Inscription_sess')->findOneBy(array('session' => $item, 'user' => $user));
        if($inscr){
            return $inscr->getRole();
        }
        return null;
    }
    public function getDateInscr($user, $item)
    {
        $em = $this->getEntityManager();

        /* @var $inscr Inscription_sess */
        $inscr = $em->getRepository('AppBundle:Inscription_sess')->findOneBy(array('session' => $item, 'user' => $user));
        if($inscr){
            return $inscr->getDateInscription();
        }
        return null;
    }

    public function getUsersInscr($session){
        $em = $this->getEntityManager();
        $inscs = $em->getRepository('AppBundle:Inscription_sess')->findBy(array('session' => $session));
        $users = [];
        if($inscs){
            /* @var $insc Inscription_sess */
            foreach ($inscs as $insc){
                $user = $insc->getUser();
                if(!in_array($insc, $users) && $user->isEnabled()) {
                    array_push($users, $user);
                }
            }
        }
        return $users;
    }
}
