<?php

namespace AppBundle\Repository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function userIsInscrit($userId, $sessId)
    {
        $em = $this->getEntityManager();
        $session = $this->findOneBy(array('id'=> $sessId));
        $user = $em->getRepository('AppBundle:User')->findOneBy(array('id' => $userId));

        $inscSess = $em->getRepository('AppBundle:Inscription_sess')->findBy(array('session' => $session, 'user' => $user));

        return $inscSess;
    }

    public function userHasAccess($userId, $sessId)
    {
        return $this->userIsInscrit($userId, $sessId);
    }

    public function userHasAccessOrIsInscrit($userId, $sessId)
    {
        return $this->userHasAccess($userId, $sessId) || $this->userIsInscrit($userId, $sessId);
    }
    public function getRole($userId, $id)
    {
        $em = $this->getEntityManager();
        $item = $this->findOneBy(array('id'=> $id));
        $user = $em->getRepository('AppBundle:User')->findOneBy(array('id' => $userId));

        $inscr = $em->getRepository('AppBundle:Inscription_sess')->findOneBy(array('session' => $item, 'user' => $user));
        if($inscr){
            return $inscr->getRole();
        }
        return null;
    }
}
