<?php

namespace AppBundle\Repository;

/**
 * SessionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SessionRepository extends \Doctrine\ORM\EntityRepository
{
    public function userIsInscrit($user, $session)
    {
        $em = $this->getEntityManager();

        $inscSess = $em->getRepository('AppBundle:Inscription_sess')->findBy(array('session' => $session, 'user' => $user));

        return $inscSess;
    }

    public function userHasAccess($user, $sess)
    {
        return $this->userIsInscrit($user, $sess);
    }

    public function userHasAccessOrIsInscrit($user, $sess)
    {
        return $this->userHasAccess($user, $sess) || $this->userIsInscrit($user, $sess);
    }
    public function getRole($user, $item)
    {
        $em = $this->getEntityManager();

        $inscr = $em->getRepository('AppBundle:Inscription_sess')->findOneBy(array('session' => $item, 'user' => $user));
        if($inscr){
            return $inscr->getRole();
        }
        return null;
    }
}
