<?php

namespace AppBundle\Repository;

/**
 * AssocDocCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssocDocCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
