<?php

namespace AppBundle\Repository;

/**
 * StatsUsersDocsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StatsUsersDocsRepository extends \Doctrine\ORM\EntityRepository
{
}
