<?php

namespace AppBundle\Repository;

/**
 * TypeLienRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeLienRepository extends \Doctrine\ORM\EntityRepository
{
}
