<?php

namespace AppBundle\Repository;

/**
 * UserStatCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStatCoursRepository extends \Doctrine\ORM\EntityRepository
{
}
