<?php

namespace AppBundle\Repository;

/**
 * UserStatLoginRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStatLoginRepository extends \Doctrine\ORM\EntityRepository
{
}
