<?php

namespace AppBundle\Repository;

/**
 * UserStatRessourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStatRessourceRepository extends \Doctrine\ORM\EntityRepository
{
}
