<?php

namespace AppBundle\Repository;
use AppBundle\Entity\UserStatCours;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * UserStatCoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStatCoursRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbyUser($user)
    {
        $em = $this->getEntityManager();
        $UserStatCourses = $em->getRepository('AppBundle:UserStatCours')->findBy(array('user' => $user));

        $stats = new ArrayCollection();
        if ($UserStatCourses) {
            /* @var UserStatCours $statCours */
            foreach ($UserStatCourses as $statCours) {
                if ($statCours->getCours()) {
                    $stats->add($statCours);
                }
            }
        }
        return $stats;
    }
}
