<?php

namespace AppBundle\Repository;
use AppBundle\Entity\UserStatRessource;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * UserStatRessourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserStatRessourceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findbyUser($user)
    {
        $em = $this->getEntityManager();
        $UserStatRessources = $em->getRepository('AppBundle:UserStatRessource')->findBy(array('user' => $user));

        $stats = new ArrayCollection();
        if ($UserStatRessources) {
            /* @var UserStatRessource $statRessource */
            foreach ($UserStatRessources as $statRessource) {
                if ($statRessource->getRessource()) {
                    $stats->add($statRessource);
                }
            }
        }
        return $stats;
    }
}
