<?php

namespace AppBundle\Repository;

/**
 * ZoneRessourceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZoneRessourceRepository extends \Doctrine\ORM\EntityRepository
{

}
