# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    dateLimiNotifs: 2019-01-01 00:00:00
    upload_directory: 'var/upload/'
    upload_steps: '../'
    upload_srcSteps: '../'
    upload_course: '../../'
    distant_host: 'stdi.nfrance.com'
    distant_user: 'chamilo'
    distant_password: 'xserve'
    distant_database: 'chamilo'
    admin_password_init: '+JeSuisAfadecAdmin2017+'
    template: 'afadec'
    grouped_mails_limit: 2

services:
    notifsSender:
        class: AppBundle\Service\NotifsSender
        arguments: ['@doctrine.orm.entity_manager', '@mailer', '@twig', %dateLimiNotifs%]

    admin.cours:
        class: AppBundle\Admin\CoursAdmin
        arguments: [~, AppBundle\Entity\Cours, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Cours, group: "Cours" }
    admin.session:
            class: AppBundle\Admin\SessionAdmin
            arguments: [~, AppBundle\Entity\Session, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Session, group: "Cours" }
    admin.discipline:
        class: AppBundle\Admin\DisciplineAdmin
        arguments: [~, AppBundle\Entity\Discipline, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Disciplines, group: "Cours" }

    admin.evtUser:
        class: AppBundle\Admin\Evt_userAdmin
        arguments: [~, AppBundle\Entity\Evt_user, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Evènements utilisateurs, group: "Calendrier" }
    admin.evtDiscipline:
        class: AppBundle\Admin\Evt_disciplineAdmin
        arguments: [~, AppBundle\Entity\Evt_discipline, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Evènements de discipline, group: "Calendrier" }
    admin.evtCours:
        class: AppBundle\Admin\Evt_coursAdmin
        arguments: [~, AppBundle\Entity\Evt_cours, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Evènements de cours, group: "Calendrier" }

    admin.cohorte:
            class: AppBundle\Admin\CohorteAdmin
            arguments: [~, AppBundle\Entity\Cohorte, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Cohortes, group: "Inscriptions" }
    admin.inscrCoh:
        class: AppBundle\Admin\InscrCohAdmin
        arguments: [~, AppBundle\Entity\Inscription_coh, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Inscription cohorte, group: "Inscriptions" }
    admin.inscrDiscipline:
        class: AppBundle\Admin\InscrDisciplineAdmin
        arguments: [~, AppBundle\Entity\Inscription_d, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Inscription discipline, group: "Inscriptions" }
    admin.inscrCours:
        class: AppBundle\Admin\InscrCoursAdmin
        arguments: [~, AppBundle\Entity\Inscription_c, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Inscription cours, group: "Inscriptions" }
    admin.inscrSession:
        class: AppBundle\Admin\InscrSessAdmin
        arguments: [~, AppBundle\Entity\Inscription_sess, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Inscription session, group: "Inscriptions" }
    admin.roles:
        class: AppBundle\Admin\RoleAdmin
        arguments: [~, AppBundle\Entity\Role, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Roles, group: "Inscriptions" }

    admin.chat:
        class: AppBundle\Admin\ChatAdmin
        arguments: [~, AppBundle\Entity\Chat, ~]
        tags:
            - { name: sonata.admin,manager_type: orm, label: Chats, group: "Ressources" }
    admin.forum:
        class: AppBundle\Admin\ForumAdmin
        arguments: [~, AppBundle\Entity\Forum, ~]
        tags:
            - { name: sonata.admin,manager_type: orm, label: Forums, group: "Ressources" }
    admin.sujet:
        class: AppBundle\Admin\ForumSujetAdmin
        arguments: [~, AppBundle\Entity\ForumSujet, ~]
        tags:
            - { name: sonata.admin,manager_type: orm, label: Forums->Sujets, group: "Ressources" }
    admin.categorieLien:
        class: AppBundle\Admin\CategorieLienAdmin
        arguments: [~, AppBundle\Entity\CategorieLien, ~]
        tags:
            - { name: sonata.admin,manager_type: orm, label: Catégories des liens, group: "Ressources" }
    admin.typeLien:
        class: AppBundle\Admin\TypeLienAdmin
        arguments: [~, AppBundle\Entity\TypeLien, ~]
        tags:
            - { name: sonata.admin,manager_type: orm, label: Types de liens, group: "Ressources" }

    admin.institut:
        class: AppBundle\Admin\InstitutAdmin
        arguments: [~, AppBundle\Entity\Institut, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Instituts, group: "Utilisateurs" }
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Utilisateurs, group: "Utilisateurs" }
    admin.logs:
        class: AppBundle\Admin\LogAdmin
        arguments: [~, AppBundle\Entity\Log, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Logs, group: "Administration" }

    chat.topic_sample_service:
        class: AppBundle\Service\Chat\ChatTopic
        arguments: ['@gos_web_socket.websocket.client_manipulator']

    authentication.success.listener:
        class: AppBundle\EventListener\AuthenticationEventListener
        arguments: ['@router', '@service_container', '@doctrine.orm.entity_manager', "@security.token_storage"]