# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

    admin.cohorte:
        class: AppBundle\Admin\CohorteAdmin
        arguments: [~, AppBundle\Entity\Cohorte, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Cohortes, group: "Cours" }
    admin.cours:
        class: AppBundle\Admin\CoursAdmin
        arguments: [~, AppBundle\Entity\Cours, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Cours, group: "Cours" }
    admin.session:
            class: AppBundle\Admin\SessionAdmin
            arguments: [~, AppBundle\Entity\Session, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, label: Session, group: "Cours" }
    admin.discipline:
        class: AppBundle\Admin\DisciplineAdmin
        arguments: [~, AppBundle\Entity\Discipline, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Disciplines, group: "Cours" }
    admin.institut:
        class: AppBundle\Admin\InstitutAdmin
        arguments: [~, AppBundle\Entity\Institut, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Instituts, group: "Utilisateurs" }
    admin.user:
        class: AppBundle\Admin\UserAdmin
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Utilisateurs, group: "Utilisateurs" }


    admin.forum:
        class: AppBundle\Admin\ForumAdmin
        arguments: [~, AppBundle\Entity\Forum, ~]
        tags:
            - { name: sonata.admin,manager_type: orm, label: Forums, group: "Ressources" }
    admin.sujet:
        class: AppBundle\Admin\ForumSujetAdmin
        arguments: [~, AppBundle\Entity\ForumSujet, ~]
        tags:
            - { name: sonata.admin,manager_type: orm, label: Forums->Sujets, group: "Ressources" }
    admin.categorieLien:
        class: AppBundle\Admin\CategorieLienAdmin
        arguments: [~, AppBundle\Entity\CategorieLien, ~]
        tags:
            - { name: sonata.admin,manager_type: orm, label: Catégories des liens, group: "Ressources" }
    admin.typeLien:
        class: AppBundle\Admin\TypeLienAdmin
        arguments: [~, AppBundle\Entity\TypeLien, ~]
        tags:
            - { name: sonata.admin,manager_type: orm, label: Types de liens, group: "Ressources" }

    admin.evtUser:
        class: AppBundle\Admin\Evt_userAdmin
        arguments: [~, AppBundle\Entity\Evt_user, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Evènements utilisateurs, group: "Calendrier" }
    admin.evtDiscipline:
        class: AppBundle\Admin\Evt_disciplineAdmin
        arguments: [~, AppBundle\Entity\Evt_discipline, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Evènements de discipline, group: "Calendrier" }
    admin.evtCours:
        class: AppBundle\Admin\Evt_coursAdmin
        arguments: [~, AppBundle\Entity\Evt_cours, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Evènements de cours, group: "Calendrier" }

    chat.topic_sample_service:
        class: AppBundle\Service\Chat\ChatTopic
        arguments: ['@gos_web_socket.websocket.client_manipulator']